name: pypo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  percent_indicator: ^4.2.5
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  permission_handler: ^10.2.0
  logger: ^1.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/PyPo_logo.png

# Konfigurasi launcher icon (flutter_launcher_icons)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/PyPo_logo.png"
